<?php

use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function csc_site_blocks_theme() {
  return [
    'csc_skewed_block' => [
      'variables' => [
        'bgcolor' => '',
        'divheight' => '',
        'skewheight' => '',
        'angle' => '',
        'marginbottom' => '',
      ],
    ],
  ];
}

function csc_logit($msg='no message sent to log function', $ltype='notice', $sufx='') {
  if (strlen($sufx) > 0) { $sufx = " $sufx"; }
  if ($ltype == 'warning') {
    Drupal::logger("csc_bs_sass$sufx")->warning($msg);
  } elseif ($ltype == 'error') {
    Drupal::logger("csc_bs_sass$sufx")->error($msg);
  } else {
    Drupal::logger("csc_bs_sass$sufx")->notice($msg);
  }
}

